# Generated by Django 5.0 on 2023-12-28 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0002_alter_snippet_options_snippet_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippet',
            options={},
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='created',
        ),
    ]
