# Generated by Django 5.0 on 2024-01-02 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='user',
            new_name='owner',
        ),
    ]
